### ISSUE TITLE
TypeError: transcribe() got an unexpected keyword argument 'repetition_penalty'

### ISSUE THREAD

**Issue by hhhynnn** [zh-plus/openlrc#21]
执行 lrcer.run('./data/p1.mp3', arget_lang='zh-cn', skip_trans=True) 报错

Traceback (most recent call last):
  File "/root/autodl-tmp/code/audio2text/openlrc_test.py", line 7, in <module>
    lrcer.run('./data/p1.mp3',
  File "/root/miniconda3/envs/audio/lib/python3.9/site-packages/openlrc/openlrc.py", line 243, in run
    producer.result()
  File "/root/miniconda3/envs/audio/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/root/miniconda3/envs/audio/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/audio/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/audio/lib/python3.9/site-packages/openlrc/openlrc.py", line 83, in transcription_producer
    segments, info = self.transcriber.transcribe(audio_path, language=src_lang)
  File "/root/miniconda3/envs/audio/lib/python3.9/site-packages/openlrc/transcribe.py", line 36, in transcribe
    seg_gen, info = self.whisper_model.transcribe(str(audio_path), language=language,
TypeError: transcribe() got an unexpected keyword argument 'repetition_penalty

经过检查，0.2.3 版本 的 openlrc.py 里定义的 transcribe() 函数确实没有 repetition_penalty 参数

**Comment by hhhynnn** [comment]
说错了，transcribe() 是 transcrib.py 里定义的，没有 repetition_penalty 参数是因为 faster-whipser 版本低，换成0.8.0就行了;

$ pip install faster-whisper==0.8.0

但是会有警告：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openlrc 0.2.3 requires faster-whisper<0.8.0,>=0.7.1, but you have faster-whisper 0.8.0 which is incompatible

也就是说跟着 README.md 一定会导致下载到错误的 faster-whisper 版本

**Comment by zh-plus** [comment]
The `faster-whisper` dependency will be updated in the upcoming release. I'm still waiting for https://github.com/SYSTRAN/faster-whisper/pull/548 to be merged.
