### ISSUE TITLE
TypeError: WhisperModel.transcribe() got an unexpected keyword argument 'hotwords'

### ISSUE THREAD

**Issue by popcion** [zh-plus/openlrc#38]
Traceback (most recent call last):
  File "G:\test\q.py", line 4, in <module>
    lrcer.run(['q.mp3', 'w.mp3'], target_lang='zh-cn')
  File "F:\Program Files\Python-3.11.4\Lib\site-packages\openlrc\openlrc.py", line 320, in run
    producer.result()
  File "F:\Program Files\Python-3.11.4\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "F:\Program Files\Python-3.11.4\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "F:\Program Files\Python-3.11.4\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Program Files\Python-3.11.4\Lib\site-packages\openlrc\openlrc.py", line 119, in transcription_producer
    segments, info = self.transcriber.transcribe(audio_path, language=src_lang)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Program Files\Python-3.11.4\Lib\site-packages\openlrc\transcribe.py", line 41, in transcribe
    seg_gen, info = self.whisper_model.transcribe(str(audio_path), language=language,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
![photo_2024-05-22_02-26-34](https://github.com/zh-plus/openlrc/assets/170460140/0c69dea5-6b81-4daa-8276-df3f64fca92d)

**Comment by zh-plus** [comment]
Upgrade `faster-whisper` to the latest version using:
```
pip install -U faster-whisper
```

**Comment by popcion** [comment]
Solved.
by the way, Glossary doesn't work, neither in .py files nor .yaml. when I translated from Japanese to Chinese. words do not remain the same
eg. "おじさん">"爺爺"/“老頭”

lrcer = LRCer(glossary={
    "おじさーん": "叔叔", 
    "おじさん": "叔叔", 
    })
